dist: trusty
sudo: required

# we disable the new recursive submodule initialization
# (https://github.com/travis-ci/travis-ci/issues/4099)
# because we don't need the recursive submodules and some would fail
# due to ssh urls
git:
  submodules: false

# default is ruby, we set python in case we need to do some
# advanced scripting in our setup of the C++ tests
language: python

matrix:
  include:
    - os: linux
      services: docker
      # omit -fsanitize=undefined for now as its message inject
      # a memory leak ...
      env: docker_img=gsauthof/fedora-cxx-devel:29 build_method=meson build_type=debug build_flags=-Db_coverage=true CXXFLAGS="-fsanitize=address" targets="ut imapdl" UT_PREFIX=/srv/src/unittest
      python: 3.5

before_install:
  - git submodule update --init # cf. above `git:` section
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/before_install.sh

install:
  - docker exec --user root devel dnf -y install cryptopp-devel
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/install.sh

before_script:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/before_script.sh

script:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/script.sh

after_success:
  - ./ci/travis/"$TRAVIS_OS_NAME$tag"/after_success.sh
